//! The Codewhale mark — the founder raster in braille dots (2×4 per cell).
//!
//! The rows are generated, never hand-drawn: `scripts/brand/braille-mark.py`
//! reads the canonical product mark (`brand/codewhalemarkfinal.png`, PRD
//! section 6: the white whale on the navy rounded square) and derives the
//! hero whale's navy darkness down to a dot grid (threshold 0.3, aspect
//! preserved and centred in the rung's box, all-blank edge columns trimmed,
//! the eye carved as one cleared dot). No redraws, no traced SVG: the dots
//! are a proportional derivative of the founder file. Two rungs from the
//! boxes: [`MarkSize::Small`] (box 11×3 → ink 7×3) and [`MarkSize::Tiny`]
//! (box 8×2 → ink 5×2). The ASCII lane has no mark at all:
//! `glyphs::ascii_fallback` flattens braille to `#`, so the wordmark line
//! stands alone there.
//!
//! The active mark uses braille and kitty graphics:
//!
//! - [`render_mark`] paints the braille rows (every terminal).
//! - On terminals that answer the kitty graphics query
//!   ([`probe_kitty_graphics`]) the launch header paints
//!   [`render_kitty_placeholders`] instead: Unicode placeholder cells the
//!   terminal replaces with the PNG transmitted once by
//!   [`transmit_kitty_mark`]. ratatui's buffer still owns the cells, so the
//!   image survives redraws.
//! Motion ("surfacing", founder 2026-09-01): over `MARK_SURFACE_MS` the mark
//! reveals from the bottom of its box upward — the whale rises out of the
//! field — while its colour lerps from the field to the accent through
//! [`surface_progress`]'s raised-cosine ease. Then it holds still forever.
//! Reduced motion passes `progress = 1.0`, which is this same drawing at its
//! endpoint, so the still frame cannot drift from the animated one.

use std::io::Write;
use std::sync::OnceLock;

use ratatui::style::Color;

/// Rungs of the mark's scale ladder, each generated at its own box.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum MarkSize {
    /// Box 22×6, ink 14×6 — the launch screen's hero mark. Generated from the
    /// same founder raster as the smaller rungs, at a size where the whale
    /// reads as a whale.
    Large,
    /// Box 11×3, ink 7×3 — the launch header's mark.
    Small,
    /// Box 8×2, ink 5×2 — for stages too narrow for the header lines beside
    /// the small rung.
    Tiny,
}

// generated by scripts/brand/braille-mark.py from brand/codewhalemarkfinal.png
// (founder hero whale 504x453px, threshold 0.3, aspect preserved,
// edge columns trimmed, eye carved)

// LARGE: box 22x6 -> ink 14x6
const LARGE_ROWS: [&str; 6] = [
    "  ⣀⣴⣶⣾⣶⣆      ",
    "⢀⣼⣿⠛⠉⠉⠙⠻⠟⠃    ",
    "⢸⣿⡇    ⢀⣀⣤⣤⣤⣤⡀",
    "⢸⣿⣷⣤⣤⣶⣿⣿⣿⡿⠟⠉⣹⠁",
    "⠈⢻⣿⣿⣿⣿⣿⣷⠟ ⢀⡴⠁ ",
    "  ⠈⠉⠽⠿⣿⠥⠤⠒⠉   ",
];

// SMALL: box 11x3 -> ink 7x3
const SMALL_ROWS: [&str; 3] = [
    "⢠⡶⠛⠧⠄  ", //
    "⣿⣄⣠⣤⣶⠶⠆",
    "⠘⠻⣿⣗⠡⠊ ",
];

// TINY: box 8x2 -> ink 5x2
const TINY_ROWS: [&str; 2] = [
    "⢠⡞⠛⢂⣀", //
    "⠘⠿⣿⠍⠉",
];

impl MarkSize {
    /// Cell footprint as `(cols, rows)` — the ink's, not the design box's.
    #[must_use]
    pub const fn cells(self) -> (u16, u16) {
        match self {
            Self::Large => (14, 6),
            Self::Small => (7, 3),
            Self::Tiny => (5, 2),
        }
    }

    /// The braille rows for this rung. Blank cells are spaces so the
    /// renderer leaves the field behind them untouched.
    #[must_use]
    pub const fn rows(self) -> &'static [&'static str] {
        match self {
            Self::Large => &LARGE_ROWS,
            Self::Small => &SMALL_ROWS,
            Self::Tiny => &TINY_ROWS,
        }
    }
}

/// Blend `from` toward `to` (0.0 → `from`, 1.0 → `to`). At 0 the mark is
/// exactly the field colour, so it rises out of the water rather than over it.
#[must_use]
pub fn lerp_color(from: Color, to: Color, amount: f32) -> Color {
    let amount = amount.clamp(0.0, 1.0);
    match (from, to) {
        (Color::Rgb(fr, fg, fb), Color::Rgb(tr, tg, tb)) => Color::Rgb(
            lerp_channel(fr, tr, amount),
            lerp_channel(fg, tg, amount),
            lerp_channel(fb, tb, amount),
        ),
        // Indexed colours have no channels to interpolate; snap at midpoint.
        _ => {
            if amount >= 0.5 {
                to
            } else {
                from
            }
        }
    }
}

fn lerp_channel(from: u8, to: u8, amount: f32) -> u8 {
    let from = f32::from(from);
    let to = f32::from(to);
    (from + (to - from) * amount).round().clamp(0.0, 255.0) as u8
}

/// Raised-cosine rise over `duration_ms`, saturating at 1.0. Wall-clock keyed,
/// so a dropped frame costs smoothness, never correctness.
#[must_use]
pub fn surface_progress(elapsed_ms: u128, duration_ms: u128) -> f32 {
    if duration_ms == 0 || elapsed_ms >= duration_ms {
        return 1.0;
    }
    let t = elapsed_ms as f32 / duration_ms as f32;
    0.5 * (1.0 - (std::f32::consts::PI * t).cos())
}

// ---------------------------------------------------------------------------
// Kitty graphics tier.
//
// Protocol: https://sw.kovidgoyal.net/kitty/graphics-protocol/ — the image is
// transmitted once as base64 PNG chunks (`a=T,f=100`), given a *virtual*
// placement (`a=p,U=1`) sized in cells, and then shown wherever the screen
// holds placeholder cells: U+10EEEE with the image id in the foreground
// colour and the row/column encoded as combining diacritics. Those are
// ordinary cells to ratatui, so the diff, the alternate screen and redraws
// all keep the image where the buffer says it is.
// ---------------------------------------------------------------------------

/// Image id of the mark. Kept ≤ 255 so the placeholder foreground is an
/// indexed colour, which every palette-adaptation stage leaves untouched
/// (only RGB foregrounds are theme-remapped or contrast-lifted).
pub const KITTY_MARK_IMAGE_ID: u8 = 31;
/// A cell is about 1:2, so this 6×3 Kitty placeholder block is square like
/// the founder app-icon PNG.
pub const MARK_IMAGE_COLS: u16 = 6;
pub const MARK_IMAGE_ROWS: u16 = 3;
/// Cell heights from here up get the 96 px raster; smaller cells get 48 px.
const KITTY_LARGE_CELL_PX: u16 = 24;

const MARK_PNG_96: &[u8] = include_bytes!("../../assets/mark-96.png");
const MARK_PNG_48: &[u8] = include_bytes!("../../assets/mark-48.png");

/// Capability query: a 1×1 RGB image sent with `a=q` is validated but never
/// stored; a supporting terminal answers `ESC _ G i=31;OK ESC \`.
const KITTY_QUERY: &[u8] = b"\x1b_Gi=31,s=1,v=1,a=q,t=d,f=24;AAAA\x1b\\";
/// A terminal that supports the protocol answers within a millisecond.
const KITTY_QUERY_TIMEOUT: std::time::Duration = std::time::Duration::from_millis(120);
/// Base64 payload per chunk (the protocol's maximum is 4096).
const KITTY_CHUNK: usize = 4096;

static KITTY_GRAPHICS: OnceLock<bool> = OnceLock::new();

/// Environments worth asking. The query is only issued where the terminal is
/// one that could answer, so terminals that will never reply do not pay the
/// timeout at startup. tmux is excluded: image data needs a passthrough
/// wrapper there, which this tier does not do.
fn kitty_candidate_env(env: impl Fn(&str) -> Option<String>) -> bool {
    if env("TMUX").is_some() {
        return false;
    }
    let term = env("TERM").unwrap_or_default().to_ascii_lowercase();
    let program = env("TERM_PROGRAM").unwrap_or_default().to_ascii_lowercase();
    term.contains("kitty")
        || term.contains("ghostty")
        || matches!(
            program.as_str(),
            "kitty" | "wezterm" | "ghostty" | "konsole"
        )
        || env("KITTY_WINDOW_ID").is_some()
        || env("KONSOLE_VERSION").is_some()
}

/// The terminal's answer to the capability query, decided: `OK` means it
/// validated our image; anything else (an error, no reply) does not.
fn kitty_query_accepted(reply: Option<&[u8]>) -> bool {
    reply.is_some_and(|reply| {
        let text = String::from_utf8_lossy(reply);
        text.contains("_G") && text.contains(";OK")
    })
}

/// Ask the terminal once whether it draws kitty graphics, and cache the
/// answer for the process. Call from the TUI entry point in the same window
/// as `codewhale_palette::probe_terminal_background` — raw mode on, event loop not yet
/// reading stdin — since the reply comes back on stdin.
pub fn probe_kitty_graphics() -> bool {
    *KITTY_GRAPHICS.get_or_init(|| {
        kitty_candidate_env(|key| std::env::var(key).ok())
            && kitty_query_accepted(
                codewhale_palette::osc11::query_terminal(KITTY_QUERY, KITTY_QUERY_TIMEOUT)
                    .as_deref(),
            )
    })
}

/// Whether the probe said yes. `false` before the probe runs, so a render
/// that outruns startup paints the braille tier rather than empty cells.
#[must_use]
pub fn kitty_graphics_supported() -> bool {
    KITTY_GRAPHICS.get().copied().unwrap_or(false)
}

/// The byte stream that transmits `png` as image `id` and gives it a virtual
/// placement `cols`×`rows` cells. `q=2` silences the terminal's replies so
/// nothing lands in the input stream.
#[must_use]
pub fn kitty_transmit_sequence(png: &[u8], id: u8, cols: u16, rows: u16) -> Vec<u8> {
    use base64::{Engine as _, engine::general_purpose::STANDARD};
    let encoded = STANDARD.encode(png);
    let chunks: Vec<&[u8]> = encoded.as_bytes().chunks(KITTY_CHUNK).collect();
    let mut out = Vec::with_capacity(encoded.len() + 64 * chunks.len());
    for (index, chunk) in chunks.iter().enumerate() {
        let more = u8::from(index + 1 < chunks.len());
        if index == 0 {
            out.extend_from_slice(format!("\x1b_Ga=T,f=100,q=2,i={id},m={more};").as_bytes());
        } else {
            out.extend_from_slice(format!("\x1b_Gm={more};").as_bytes());
        }
        out.extend_from_slice(chunk);
        out.extend_from_slice(b"\x1b\\");
    }
    out.extend_from_slice(format!("\x1b_Ga=p,U=1,q=2,i={id},c={cols},r={rows}\x1b\\").as_bytes());
    out
}

/// The byte stream that deletes image `id` and frees its data (`d=I`).
#[must_use]
pub fn kitty_delete_sequence(id: u8) -> Vec<u8> {
    format!("\x1b_Ga=d,d=I,q=2,i={id}\x1b\\").into_bytes()
}

/// Pick the raster for the terminal's cell height (`None` → the large one).
fn kitty_mark_png(cell_height_px: Option<u16>) -> &'static [u8] {
    match cell_height_px {
        Some(px) if px < KITTY_LARGE_CELL_PX => MARK_PNG_48,
        _ => MARK_PNG_96,
    }
}

/// Transmit the mark once, if the probe said the terminal draws it. Cheap
/// no-op otherwise. Write errors are logged, never fatal: a mark that fails
/// to upload simply leaves the placeholder cells blank until the next paint
/// falls back to braille.
pub fn transmit_kitty_mark<W: Write>(writer: &mut W, cell_height_px: Option<u16>) {
    if !kitty_graphics_supported() {
        return;
    }
    let bytes = kitty_transmit_sequence(
        kitty_mark_png(cell_height_px),
        KITTY_MARK_IMAGE_ID,
        MARK_IMAGE_COLS,
        MARK_IMAGE_ROWS,
    );
    if let Err(err) = writer.write_all(&bytes).and_then(|()| writer.flush()) {
        tracing::debug!(target: "kitty_graphics", ?err, "mark transmission failed");
    }
}

/// Delete the transmitted mark on the way out so the terminal frees it.
pub fn delete_kitty_mark<W: Write>(writer: &mut W) {
    if !kitty_graphics_supported() {
        return;
    }
    let bytes = kitty_delete_sequence(KITTY_MARK_IMAGE_ID);
    if let Err(err) = writer.write_all(&bytes).and_then(|()| writer.flush()) {
        tracing::debug!(target: "kitty_graphics", ?err, "mark deletion failed");
    }
}

// ---------------------------------------------------------------------------
// Sixel graphics tier.
//
// For terminals that draw sixel (foot, mlterm, contour, sixel-enabled xterm,
// WezTerm with kitty graphics off) but never answered the kitty query.
// Keep the capability probe for the terminal receipt; launch has no sixel renderer.
// ---------------------------------------------------------------------------

/// Primary device-attributes request. A sixel terminal answers with its
/// capability parameters, e.g. `ESC [ ? 62 ; 4 c` (foot) or
/// `ESC [ ? 63 ; 1 ; 2 ; 4 ; 6 ; 7 ; 15 ; 18 c` (xterm-sixel); parameter 4 is
/// sixel graphics. Read with `query_terminal_csi`: a DA reply ends at its
/// `c` final byte, not at BEL/ST, so the shared OSC-11 reader would swallow
/// following input waiting for a terminator that never comes.
const SIXEL_QUERY: &[u8] = b"\x1b[c";
/// Same budget as the kitty query: answering terminals reply at once.
const SIXEL_QUERY_TIMEOUT: std::time::Duration = std::time::Duration::from_millis(120);
static SIXEL_GRAPHICS: OnceLock<bool> = OnceLock::new();

/// Environments worth asking. Same contract as the kitty gate: only
/// terminals that answer a DA query promptly, never tmux (image data needs
/// a passthrough wrapper there, which this tier does not do). The DA reply
/// itself decides — `xterm-256color` is listed because Terminal.app, iTerm2
/// and xterm.js answer it at once without parameter 4, which is a fast no.
fn sixel_candidate_env(env: impl Fn(&str) -> Option<String>) -> bool {
    if env("TMUX").is_some() {
        return false;
    }
    let term = env("TERM").unwrap_or_default().to_ascii_lowercase();
    let program = env("TERM_PROGRAM").unwrap_or_default().to_ascii_lowercase();
    term.contains("foot")
        || term.contains("mlterm")
        || term.contains("contour")
        || term == "xterm"
        || term.starts_with("xterm-")
        || term == "st"
        || term.starts_with("st-")
        || program.as_str() == "wezterm"
}

/// The terminal's answer to the primary-DA query, decided: parameter `4`
/// (sixel graphics) present means it draws sixel; anything else does not.
fn da_reports_sixel(reply: Option<&[u8]>) -> bool {
    let Some(reply) = reply else {
        return false;
    };
    let text = String::from_utf8_lossy(reply);
    text.split('\x1b').any(|chunk| {
        let body = chunk.strip_prefix("[?").or_else(|| chunk.strip_prefix("["));
        body.is_some_and(|body| {
            body.strip_suffix('c')
                .is_some_and(|params| params.split(';').any(|param| param == "4"))
        })
    })
}

/// Ask the terminal once whether it draws sixel, and cache the answer for
/// the process. Call after [`probe_kitty_graphics`] in the same pre-loop
/// window (raw mode on, event loop not yet reading stdin): kitty answers
/// its own query, so reaching here means the terminal speaks another
/// protocol, and the launch header prefers kitty wherever both answer.
pub fn probe_sixel_graphics() -> bool {
    *SIXEL_GRAPHICS.get_or_init(|| {
        !kitty_graphics_supported()
            && sixel_candidate_env(|key| std::env::var(key).ok())
            && da_reports_sixel(
                codewhale_palette::osc11::query_terminal_csi(SIXEL_QUERY, SIXEL_QUERY_TIMEOUT)
                    .as_deref(),
            )
    })
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn every_rung_matches_its_declared_footprint_in_braille_only() {
        for size in [MarkSize::Large, MarkSize::Small, MarkSize::Tiny] {
            let (cols, rows) = size.cells();
            let art = size.rows();
            assert_eq!(art.len(), usize::from(rows), "{size:?} row count");
            for line in art {
                assert_eq!(
                    line.chars().count(),
                    usize::from(cols),
                    "{size:?} row {line:?} is not {cols} cells"
                );
                for glyph in line.chars() {
                    // U+2800..=U+28FF is the braille block. Checked directly
                    // rather than through the old buffer renderer's bit
                    // decoder, which went with that renderer.
                    assert!(
                        glyph == ' ' || ('\u{2800}'..='\u{28FF}').contains(&glyph),
                        "{size:?} row {line:?} holds a non-braille glyph {glyph:?}"
                    );
                }
            }
            // Generated rows are trimmed: the first and last columns carry ink.
            assert!(art.iter().any(|line| line.starts_with(|c| c != ' ')));
            assert!(art.iter().any(|line| line.ends_with(|c| c != ' ')));
        }
    }

    #[test]
    fn the_mark_has_an_eye() {
        // The script carves the founder whale's eye as one cleared dot
        // inside the body (bit 0x08 of the eye cell). Without the carve the
        // small rung reads `⣟` there and the tiny rung `⠏`.
        assert_eq!(
            SMALL_ROWS[2].chars().nth(3),
            Some('⣗'),
            "small rung lost its carved eye"
        );
        assert_eq!(
            TINY_ROWS[1].chars().nth(3),
            Some('⠍'),
            "tiny rung lost its carved eye"
        );
    }

    #[test]
    fn surface_progress_is_a_monotonic_rise_that_settles_at_one() {
        assert!((surface_progress(0, 640) - 0.0).abs() < 1e-6);
        assert!((surface_progress(320, 640) - 0.5).abs() < 1e-3);
        assert!((surface_progress(640, 640) - 1.0).abs() < 1e-6);
        assert!((surface_progress(5_000, 640) - 1.0).abs() < 1e-6);
        let mut previous = -1.0;
        for ms in (0..=640).step_by(20) {
            let value = surface_progress(ms, 640);
            assert!(value >= previous, "regressed at {ms}ms");
            previous = value;
        }
    }

    #[test]
    fn a_zero_length_rise_is_settled_not_divided_by_zero() {
        assert!((surface_progress(0, 0) - 1.0).abs() < 1e-6);
    }

    #[test]
    fn kitty_candidates_are_the_terminals_that_can_answer_and_never_tmux() {
        let env = |vars: &[(&str, &str)]| {
            let vars: Vec<(String, String)> = vars
                .iter()
                .map(|(k, v)| (k.to_string(), v.to_string()))
                .collect();
            move |key: &str| vars.iter().find(|(k, _)| k == key).map(|(_, v)| v.clone())
        };
        assert!(kitty_candidate_env(env(&[("TERM", "xterm-kitty")])));
        assert!(kitty_candidate_env(env(&[("TERM_PROGRAM", "WezTerm")])));
        assert!(kitty_candidate_env(env(&[("TERM", "xterm-ghostty")])));
        assert!(kitty_candidate_env(env(&[("KONSOLE_VERSION", "230800")])));
        assert!(!kitty_candidate_env(env(&[
            ("TERM", "xterm-256color"),
            ("TERM_PROGRAM", "Apple_Terminal")
        ])));
        assert!(!kitty_candidate_env(env(&[
            ("TERM", "xterm-kitty"),
            ("TMUX", "/tmp/tmux-501/default,1,0")
        ])));
    }

    #[test]
    fn the_query_is_accepted_only_on_an_ok_reply() {
        assert!(kitty_query_accepted(Some(b"\x1b_Gi=31;OK")));
        assert!(!kitty_query_accepted(Some(b"\x1b_Gi=31;EINVAL:bad")));
        assert!(!kitty_query_accepted(Some(b"\x1b[?1;2c")));
        assert!(!kitty_query_accepted(None));
    }

    #[test]
    fn the_transmit_stream_is_chunked_png_then_a_virtual_placement() {
        let bytes = kitty_transmit_sequence(MARK_PNG_96, 31, 6, 3);
        let text = String::from_utf8(bytes).expect("ASCII stream");
        let commands: Vec<&str> = text.split("\x1b\\").filter(|s| !s.is_empty()).collect();
        assert!(commands.len() >= 3, "{} commands", commands.len());
        assert!(commands[0].starts_with("\x1b_Ga=T,f=100,q=2,i=31,m=1;"));
        for chunk in &commands[..commands.len() - 1] {
            let payload = chunk.split_once(';').map(|(_, p)| p).unwrap_or("");
            assert!(
                payload.len() <= KITTY_CHUNK,
                "chunk over 4096: {}",
                payload.len()
            );
            assert!(
                payload
                    .bytes()
                    .all(|b| b.is_ascii_alphanumeric() || b == b'+' || b == b'/' || b == b'='),
                "chunk is not base64"
            );
        }
        let last_chunk = commands[commands.len() - 2];
        assert!(
            last_chunk.starts_with("\x1b_Gm=0;"),
            "final chunk ends the upload"
        );
        assert_eq!(
            commands[commands.len() - 1],
            "\x1b_Ga=p,U=1,q=2,i=31,c=6,r=3"
        );
        // The PNG really is one: decode the payload back.
        use base64::{Engine as _, engine::general_purpose::STANDARD};
        let payload: String = commands[..commands.len() - 1]
            .iter()
            .map(|chunk| chunk.split_once(';').map(|(_, p)| p).unwrap_or(""))
            .collect();
        let decoded = STANDARD.decode(payload).expect("base64 round-trips");
        assert_eq!(decoded, MARK_PNG_96);
        assert!(decoded.starts_with(b"\x89PNG"));
        assert_eq!(kitty_delete_sequence(31), b"\x1b_Ga=d,d=I,q=2,i=31\x1b\\");
    }

    #[test]
    fn the_bundled_rasters_decode_to_their_declared_sizes() {
        for (png, edge) in [(MARK_PNG_96, 96u32), (MARK_PNG_48, 48u32)] {
            let image = image::load_from_memory(png).expect("bundled mark decodes");
            assert_eq!((image.width(), image.height()), (edge, edge));
        }
        assert_eq!(kitty_mark_png(None), MARK_PNG_96);
        assert_eq!(kitty_mark_png(Some(16)), MARK_PNG_48);
        assert_eq!(kitty_mark_png(Some(32)), MARK_PNG_96);
    }
    #[test]
    fn sixel_candidates_are_the_terminals_that_answer_da_and_never_tmux() {
        let env = |vars: &[(&str, &str)]| {
            let vars: Vec<(String, String)> = vars
                .iter()
                .map(|(k, v)| (k.to_string(), v.to_string()))
                .collect();
            move |key: &str| vars.iter().find(|(k, _)| k == key).map(|(_, v)| v.clone())
        };
        assert!(sixel_candidate_env(env(&[("TERM", "foot")])));
        assert!(sixel_candidate_env(env(&[("TERM", "foot-extra")])));
        assert!(sixel_candidate_env(env(&[("TERM", "mlterm")])));
        assert!(sixel_candidate_env(env(&[("TERM", "contour")])));
        // `xterm-256color` is a candidate even though most of its owners
        // decline: Terminal.app, iTerm2 and xterm.js answer DA at once
        // without parameter 4, which is a fast no rather than a timeout.
        assert!(sixel_candidate_env(env(&[("TERM", "xterm-256color")])));
        assert!(sixel_candidate_env(env(&[("TERM", "st-256color")])));
        assert!(sixel_candidate_env(env(&[("TERM_PROGRAM", "WezTerm")])));
        assert!(!sixel_candidate_env(env(&[])));
        assert!(!sixel_candidate_env(env(&[("TERM", "dumb")])));
        assert!(!sixel_candidate_env(env(&[
            ("TERM", "foot"),
            ("TMUX", "/tmp/tmux-501/default,1,0")
        ])));
    }

    #[test]
    fn the_da_reply_decides_on_parameter_four_only() {
        // foot: sixel present.
        assert!(da_reports_sixel(Some(b"\x1b[?62;4c")));
        // xterm-sixel: sixel among other capabilities.
        assert!(da_reports_sixel(Some(b"\x1b[?63;1;2;4;6;7;15;18c")));
        // Plain xterm: answers, no sixel.
        assert!(!da_reports_sixel(Some(b"\x1b[?62;1;2;6;7c")));
        // A 4 inside another parameter is not sixel.
        assert!(!da_reports_sixel(Some(b"\x1b[?62;44c")));
        // A kitty reply is not a DA reply.
        assert!(!da_reports_sixel(Some(b"\x1b_Gi=31;OK\x1b\\")));
        assert!(!da_reports_sixel(None));
    }

    #[test]
    fn the_bundled_app_icon_decodes_square_with_transparent_corners() {
        // The raster-tier PNG is the founder app icon (white whale on the
        // navy rounded square), not a monochrome silhouette: its corners
        // are transparent and its body is navy with a white whale.
        let image = image::load_from_memory(MARK_PNG_96).expect("bundled mark decodes");
        let rgba = image.to_rgba8();
        assert_eq!((rgba.width(), rgba.height()), (96, 96));
        assert_eq!(rgba.get_pixel(0, 0)[3], 0, "corner is transparent");
        let mut navy = 0usize;
        let mut white = 0usize;
        for pixel in rgba.pixels() {
            let [r, g, b, a] = pixel.0;
            if a < 128 {
                continue;
            }
            if b > 60 && u16::from(b) > u16::from(r) + 25 {
                navy += 1;
            }
            if r > 200 && g > 200 && b > 200 {
                white += 1;
            }
        }
        assert!(navy > 1000, "navy field present ({navy})");
        assert!(white > 500, "white whale present ({white})");
    }
}
